version: "3.8"
services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4    
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    networks:
      - mongodb_network
  mongodb-express:
    container_name: mongodb-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - mongodb_network
networks:
  mongodb_network:
    driver: bridge
    name: mongodb_network
